In [1]:
import torch

In [2]:
%uv pip show torch

Using Python 3.12.12 environment at: /home/test-14900/anaconda3/envs/conda-env-3-12
Name: torch
Version: 2.10.0
Location: /home/test-14900/anaconda3/envs/conda-env-3-12/lib/python3.12/site-packages
Requires: cuda-bindings, filelock, fsspec, jinja2, networkx, nvidia-cublas-cu12, nvidia-cuda-cupti-cu12, nvidia-cuda-nvrtc-cu12, nvidia-cuda-runtime-cu12, nvidia-cudnn-cu12, nvidia-cufft-cu12, nvidia-cufile-cu12, nvidia-curand-cu12, nvidia-cusolver-cu12, nvidia-cusparse-cu12, nvidia-cusparselt-cu12, nvidia-nccl-cu12, nvidia-nvjitlink-cu12, nvidia-nvshmem-cu12, nvidia-nvtx-cu12, setuptools, sympy, triton, typing-extensions
Required-by:
Note: you may need to restart the kernel to use updated packages.


In [3]:
display(torch.cuda.is_available())

False

### Introduction to tensors:
- Multidimentional array

In [10]:
# creating tensor
display(""""1. scaler tensor: tensor with 0 dimension""")

scaler=torch.tensor(42)
display(scaler)
display(scaler.ndim)
display(scaler.shape)

display("""2. vector tensor: tensor with 1 dimension""" )
vector=torch.tensor([1,2,3])
display(vector)
display(vector.ndim)
display(vector.shape)

display("""3. metrix tensor: tensor with 2 dimension""" )
matrix=torch.tensor([[1,2],[2,4],[5,6]])
display(matrix)
display(matrix.ndim)
display(matrix.shape)


display("""4. 3d tensor: tensor with dimension greater than 3""" )
d_tensor=torch.tensor([[[1,2],[2,4],[5,6]],[[7,8],[9,10],[11,12]]])
display(d_tensor)
display(d_tensor.ndim)
display(d_tensor.shape)

'"1. scaler tensor: tensor with 0 dimension'

tensor(42)

0

torch.Size([])

'2. vector tensor: tensor with 1 dimension'

tensor([1, 2, 3])

1

torch.Size([3])

'3. metrix tensor: tensor with 2 dimension'

tensor([[1, 2],
        [2, 4],
        [5, 6]])

2

torch.Size([3, 2])

'4. 3d tensor: tensor with dimension greater than 3'

tensor([[[ 1,  2],
         [ 2,  4],
         [ 5,  6]],

        [[ 7,  8],
         [ 9, 10],
         [11, 12]]])

3

torch.Size([2, 3, 2])

### GPU acceleration

In [11]:
if torch.cuda.is_available():
    gpu_tensor=vector.to('cuda')
    display("Tensor on gpu",gpu_tensor)
else:
    print("CUDA(Compute Unified Device Architecture) is not available")


CUDA(Compute Unified Device Architecture) is not available


### Torch properties:

In [20]:
print("Data type of matrix: ",matrix.dtype)
print("Dimension of matrix: ",torch.tensor([1,2,3,4]).ndim)
print("Tensor exist on which device: ",torch.tensor([1,2,3,4]).device)
print("Is tensor on CUDA:",torch.tensor([1,2,3]).is_cuda)
print("Size of matrix",torch.tensor([1,2,3,4,5]))
print("No of elements in tensor",torch.tensor([1,2,3]).numel())

Data type of matrix:  torch.int64
Dimension of matrix:  1
Tensor exist on which device:  cpu
Is tensor on CUDA: False
Size of matrix tensor([1, 2, 3, 4, 5])
No of elements in tensor 3
