In [25]:
from tensorflow.keras.preprocessing.text import one_hot

In [26]:
sentence=[
    "the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I prefer tea to coffee",
    "qml will change the paradigm of ml"
]

In [27]:
voc_size=10000

In [28]:
one_hot_repr=[one_hot(words,voc_size)for words in sentence]
one_hot_repr

[[2153, 3806, 5618, 975],
 [2153, 3806, 5618, 8052],
 [2153, 4577, 5618, 9262],
 [6889, 3747, 9262, 3905, 4253],
 [7081, 3703, 4378, 2153, 4478, 5618, 8414]]

In [29]:
# word embedding representation
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence  import pad_sequences
from tensorflow.keras.models import Sequential

In [30]:
import numpy as np

In [31]:
sentance_length=8
embedded_docs=pad_sequences(one_hot_repr,padding="pre",maxlen=sentance_length)
print(embedded_docs)

[[   0    0    0    0 2153 3806 5618  975]
 [   0    0    0    0 2153 3806 5618 8052]
 [   0    0    0    0 2153 4577 5618 9262]
 [   0    0    0 6889 3747 9262 3905 4253]
 [   0 7081 3703 4378 2153 4478 5618 8414]]


In [32]:
### feature representation
dim=10
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sentance_length))
model.compile('adam','mse')

In [33]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_2 (Embedding)         │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
model.predict(embedded_docs)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 95ms/step


array([[[-0.02663411, -0.03903797, -0.0016676 , -0.0393078 ,
          0.04940515,  0.04672344,  0.010044  , -0.01854124,
          0.04721097, -0.03275855],
        [-0.02663411, -0.03903797, -0.0016676 , -0.0393078 ,
          0.04940515,  0.04672344,  0.010044  , -0.01854124,
          0.04721097, -0.03275855],
        [-0.02663411, -0.03903797, -0.0016676 , -0.0393078 ,
          0.04940515,  0.04672344,  0.010044  , -0.01854124,
          0.04721097, -0.03275855],
        [-0.02663411, -0.03903797, -0.0016676 , -0.0393078 ,
          0.04940515,  0.04672344,  0.010044  , -0.01854124,
          0.04721097, -0.03275855],
        [ 0.03293449, -0.03908523,  0.03323228,  0.04264482,
          0.03687919,  0.03451954, -0.04127439,  0.04911477,
          0.04826299, -0.00403063],
        [-0.0396711 ,  0.04249538,  0.03123214, -0.01075039,
          0.04684979, -0.0078368 ,  0.00902028,  0.0282594 ,
         -0.04803591,  0.03261891],
        [ 0.01272634, -0.04775941,  0.04091651,  0.0

In [35]:
embedded_docs[0]

array([   0,    0,    0,    0, 2153, 3806, 5618,  975], dtype=int32)

In [37]:
model.predict(embedded_docs[0].reshape(1,-1))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 111ms/step


array([[[-0.02663411, -0.03903797, -0.0016676 , -0.0393078 ,
          0.04940515,  0.04672344,  0.010044  , -0.01854124,
          0.04721097, -0.03275855],
        [-0.02663411, -0.03903797, -0.0016676 , -0.0393078 ,
          0.04940515,  0.04672344,  0.010044  , -0.01854124,
          0.04721097, -0.03275855],
        [-0.02663411, -0.03903797, -0.0016676 , -0.0393078 ,
          0.04940515,  0.04672344,  0.010044  , -0.01854124,
          0.04721097, -0.03275855],
        [-0.02663411, -0.03903797, -0.0016676 , -0.0393078 ,
          0.04940515,  0.04672344,  0.010044  , -0.01854124,
          0.04721097, -0.03275855],
        [ 0.03293449, -0.03908523,  0.03323228,  0.04264482,
          0.03687919,  0.03451954, -0.04127439,  0.04911477,
          0.04826299, -0.00403063],
        [-0.0396711 ,  0.04249538,  0.03123214, -0.01075039,
          0.04684979, -0.0078368 ,  0.00902028,  0.0282594 ,
         -0.04803591,  0.03261891],
        [ 0.01272634, -0.04775941,  0.04091651,  0.0